# Generated by Django 4.2.2 on 2023-06-30 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='img_name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
