# Generated by Django 4.2.2 on 2023-06-30 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_category_img_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img_name',
            field=models.CharField(max_length=64),
        ),
    ]
